---
title: "Quarto Example"
author: "Jeremy Selva"
format:
  html:
    theme: 
      light: cerulean 
      dark: cyborg
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: false
    code-fold: show
    code-overflow: scroll
    code-copy: true
    code-tools: true
    code-link: true
    self-contained: false
    smooth-scroll: true
---

# R Packages used

```{r R Packages used, results='asis'}
library(DCVtestkit)
library(tibble)
```

# Data creation

```{r Data creation}
dilution_percent <- c(10, 20, 25, 40, 50, 60,
                      75, 80, 100, 125, 150,
                      10, 25, 40, 50, 60,
                      75, 80, 100, 125, 150)
dilution_batch_name <- c("B1", "B1", "B1", "B1", "B1",
                         "B1", "B1", "B1", "B1", "B1", "B1",
                         "B2", "B2", "B2", "B2", "B2",
                         "B2", "B2", "B2", "B2", "B2")
sample_name <- c("Sample_010a", "Sample_020a", "Sample_025a",
                 "Sample_040a", "Sample_050a", "Sample_060a",
                 "Sample_075a", "Sample_080a", "Sample_100a",
                 "Sample_125a", "Sample_150a",
                 "Sample_010b", "Sample_025b",
                 "Sample_040b", "Sample_050b", "Sample_060b",
                 "Sample_075b", "Sample_080b", "Sample_100b",
                 "Sample_125b", "Sample_150b")
lipid1_area_saturated <- c(5748124, 16616414, 21702718, 36191617,
                           49324541, 55618266, 66947588, 74964771,
                           75438063, 91770737, 94692060,
                           5192648, 16594991, 32507833, 46499896,
                           55388856, 62505210, 62778078, 72158161,
                           78044338, 86158414)
lipid2_area_linear <- c(31538, 53709, 69990, 101977, 146436, 180960,
                        232881, 283780, 298289, 344519, 430432,
                        25463, 63387, 90624, 131274, 138069,
                        205353, 202407, 260205, 292257, 367924)
lipid3_area_lod <- c(544, 397, 829, 1437, 1808, 2231,
                     3343, 2915, 5268, 8031, 11045,
                     500, 903, 1267, 2031, 2100,
                     3563, 4500, 5300, 8500, 10430)
lipid4_area_nonlinear <- c(380519, 485372, 478770, 474467, 531640, 576301,
                           501068, 550201, 515110, 499543, 474745,
                           197417, 322846, 478398, 423174, 418577,
                           426089, 413292, 450190, 415309, 457618)

dilution_annot <- tibble::tibble(Sample_Name = sample_name,
                                 Dilution_Batch_Name = dilution_batch_name,
                                 Dilution_Percent = dilution_percent)
lipid_data <- tibble::tibble(Sample_Name = sample_name,
                             Lipid1 = lipid1_area_saturated,
                             Lipid2 = lipid2_area_linear,
                             Lipid3 = lipid3_area_lod,
                             Lipid4 = lipid4_area_nonlinear)
```

# Create dilution table

```{r Create dilution table}
dilution_table <- create_dilution_table(dilution_annot, lipid_data,
                                        common_column = "Sample_Name",
                                        signal_var = "Area",
                                        column_group = "Transition_Name"
)
```

# Create dilution statistical summary

```{r Create dilution statistical summary}
dilution_summary <- summarise_dilution_table(dilution_table,
                                             grouping_variable = c("Transition_Name",
                                                                   "Dilution_Batch_Name"),
                                             conc_var = "Dilution_Percent",
                                             signal_var = "Area")

dilution_classified <- evaluate_linearity(dilution_summary,
                                          grouping_variable = c("Transition_Name",
                                                                "Dilution_Batch_Name"))
```

# Export results as Excel

```{r Export results as Excel}
write_summary_excel(dilution_classified, file_name = "dilution_summary.xlsx")
```

# Export results as pdf

```{r Export results as pdf}
ggplot_table <- add_ggplot_panel(dilution_table,
                                 dilution_summary = dilution_classified,
                                 grouping_variable = c("Transition_Name",
                                                       "Dilution_Batch_Name"),
                                 conc_var = "Dilution_Percent",
                                 signal_var = "Area")

# Get the list of ggplot list for each group
ggplot_list <- ggplot_table$panel

view_ggplot_pdf(ggplot_list,
                filename = "dilution_plot.pdf",
                ncol_per_page = 2,
                nrow_per_page = 2)
```

# Export results as trellis table

```{r Export results as trellis table}
trellis_table <- add_plotly_panel(dilution_table,
                                  dilution_summary = dilution_classified,
                                  grouping_variable = c("Transition_Name",
                                                        "Dilution_Batch_Name"),
                                  sample_name_var = "Sample_Name",
                                  dil_batch_var = "Dilution_Batch_Name",
                                  dil_batch_col = c("#377eb8",
                                                    "#4daf4a"),
                                  conc_var = "Dilution_Percent",
                                  conc_var_units = "%",
                                  conc_var_interval = 50,
                                  signal_var = "Area",
                                  have_plot_title = FALSE) |> 
  convert_to_cog(grouping_variable = c("Transition_Name",
                                       "Dilution_Batch_Name"),
                 panel_variable = "panel",
                 col_name_vec = "col_name_vec",
                 desc_vec = "desc_vec",
                 type_vec = "type_vec"
  )

# Pressing Render button will not create the 
# index.html file (Though it is not needed)
# Call this function via console to create index.html file
view_trellis_html(trellis_table,
                  grouping_variable = c("Transition_Name",
                                        "Dilution_Batch_Name"),
                  trellis_report_name = "Dilution_Plot",
                  trellis_report_folder = "Dilution_Plot_Folder")
```

